dist: xenial

matrix:
  include:
    - language: python
      python: 3.7
      install:
        - python -m pip install -r dev-requirements.txt
      script:
        - python -m pytest --cov=devops_spt tests
        - python -m flake8 --count devops_spt/
        - python -m flake8 --count setup.py
        - python -m flake8 --count tests/*test.py
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: ruby
      rvm:
        - 2.2
      before_script:
        - gem install awesome_bot
      script:
        - awesome_bot README.md
